//
//  SF.swift
//  SF
//
//  Created by Zach Eriksen on 7/17/19.
//  Copyright © 2019 oneleif. All rights reserved.
//

import SwiftUI

public enum SF: String, CaseIterable {
    // MARK: Circles
    case circle
    case circle_fill
    case circle_lefthalf_fill
    case circle_righthalf_fill
    // MARK: ABC Circles
    case a_circle
    case a_circle_fill
    case b_circle
    case b_circle_fill
    case c_circle
    case c_circle_fill
    case d_circle
    case d_circle_fill
    case e_circle
    case e_circle_fill
    case f_circle
    case f_circle_fill
    case g_circle
    case g_circle_fill
    case h_circle
    case h_circle_fill
    case i_circle
    case i_circle_fill
    case j_circle
    case j_circle_fill
    case k_circle
    case k_circle_fill
    case l_circle
    case l_circle_fill
    case m_circle
    case m_circle_fill
    case n_circle
    case n_circle_fill
    case o_circle
    case o_circle_fill
    case p_circle
    case p_circle_fill
    case q_circle
    case q_circle_fill
    case r_circle
    case r_circle_fill
    case s_circle
    case s_circle_fill
    case t_circle
    case t_circle_fill
    case u_circle
    case u_circle_fill
    case v_circle
    case v_circle_fill
    case w_circle
    case w_circle_fill
    case x_circle
    case x_circle_fill
    case y_circle
    case y_circle_fill
    case z_circle
    case z_circle_fill
    // MARK: Currency Circles
    case dollarsign_circle
    case dollarsign_circle_fill
    case centsign_circle
    case centsign_circle_fill
    case yensign_circle
    case yensign_circle_fill
    case sterlingsign_circle
    case sterlingsign_circle_fill
    case francsign_circle
    case francsign_circle_fill
    case florinsign_circle
    case florinsign_circle_fill
    case turkishlirasign_circle
    case turkishlirasign_circle_fill
    case rublesign_circle
    case rublesign_circle_fill
    case eurosign_circle
    case eurosign_circle_fill
    case dongsign_circle
    case dongsign_circle_fill
    case indianrupeesign_circle
    case indianrupeesign_circle_fill
    case tengesign_circle
    case tengesign_circle_fill
    case pesetasign_circle
    case pesetasign_circle_fill
    case pesosign_circle
    case pesosign_circle_fill
    case kipsign_circle
    case kipsign_circle_fill
    case wonsign_circle
    case wonsign_circle_fill
    case lirasign_circle
    case lirasign_circle_fill
    case australsign_circle
    case australsign_circle_fill
    case hryvniasign_circle
    case hryvniasign_circle_fill
    case nairasign_circle
    case nairasign_circle_fill
    case guaranisign_circle
    case guaranisign_circle_fill
    case coloncurrencysign_circle
    case coloncurrencysign_circle_fill
    case cedisign_circle
    case cedisign_circle_fill
    case cruzeirosign_circle
    case cruzeirosign_circle_fill
    case tugriksign_circle
    case tugriksign_circle_fill
    case millsign_circle
    case millsign_circle_fill
    case sheqelsign_circle
    case sheqelsign_circle_fill
    case manatsign_circle
    case manatsign_circle_fill
    case rupeesign_circle
    case rupeesign_circle_fill
    case bahtsign_circle
    case bahtsign_circle_fill
    case larisign_circle
    case larisign_circle_fill
    case bitcoinsign_circle
    case bitcoinsign_circle_fill
    // MARK: 0-9 Circles
    case _0_circle
    case _0_circle_fill
    case _1_circle
    case _1_circle_fill
    case _2_circle
    case _2_circle_fill
    case _3_circle
    case _3_circle_fill
    case _4_circle
    case _4_circle_fill
    case _4_alt_circle
    case _4_alt_circle_fill
    case _5_circle
    case _5_circle_fill
    case _6_circle
    case _6_circle_fill
    case _6_alt_circle
    case _6_alt_circle_fill
    case _7_circle
    case _7_circle_fill
    case _8_circle
    case _8_circle_fill
    case _9_circle
    case _9_circle_fill
    case _9_alt_circle
    case _9_alt_circle_fill
    // MARK: 00-50 Circles
    case _00_circle
    case _00_circle_fill
    case _01_circle
    case _01_circle_fill
    case _02_circle
    case _02_circle_fill
    case _03_circle
    case _03_circle_fill
    case _04_circle
    case _04_circle_fill
    case _05_circle
    case _05_circle_fill
    case _06_circle
    case _06_circle_fill
    case _07_circle
    case _07_circle_fill
    case _08_circle
    case _08_circle_fill
    case _09_circle
    case _09_circle_fill
    case _10_circle
    case _10_circle_fill
    case _11_circle
    case _11_circle_fill
    case _12_circle
    case _12_circle_fill
    case _13_circle
    case _13_circle_fill
    case _14_circle
    case _14_circle_fill
    case _15_circle
    case _15_circle_fill
    case _16_circle
    case _16_circle_fill
    case _17_circle
    case _17_circle_fill
    case _18_circle
    case _18_circle_fill
    case _19_circle
    case _19_circle_fill
    case _20_circle
    case _20_circle_fill
    case _21_circle
    case _21_circle_fill
    case _22_circle
    case _22_circle_fill
    case _23_circle
    case _23_circle_fill
    case _24_circle
    case _24_circle_fill
    case _25_circle
    case _25_circle_fill
    case _26_circle
    case _26_circle_fill
    case _27_circle
    case _27_circle_fill
    case _28_circle
    case _28_circle_fill
    case _29_circle
    case _29_circle_fill
    case _30_circle
    case _30_circle_fill
    case _31_circle
    case _31_circle_fill
    case _32_circle
    case _32_circle_fill
    case _33_circle
    case _33_circle_fill
    case _34_circle
    case _34_circle_fill
    case _35_circle
    case _35_circle_fill
    case _36_circle
    case _36_circle_fill
    case _37_circle
    case _37_circle_fill
    case _38_circle
    case _38_circle_fill
    case _39_circle
    case _39_circle_fill
    case _40_circle
    case _40_circle_fill
    case _41_circle
    case _41_circle_fill
    case _42_circle
    case _42_circle_fill
    case _43_circle
    case _43_circle_fill
    case _44_circle
    case _44_circle_fill
    case _45_circle
    case _45_circle_fill
    case _46_circle
    case _46_circle_fill
    case _47_circle
    case _47_circle_fill
    case _48_circle
    case _48_circle_fill
    case _49_circle
    case _49_circle_fill
    case _50_circle
    case _50_circle_fill
    // MARK: Math Symbols Circles
    case plus_circle
    case plus_circle_fill
    case minus_circle
    case minus_circle_fill
    case multiply_circle
    case multiply_circle_fill
    case divide_circle
    case divide_circle_fill
    case equal_circle
    case equal_circle_fill
    case greaterthan_circle
    case greaterthan_circle_fill
    case lessthan_circle
    case lessthan_circle_fill
    // MARK: General Symbols Circles
    case number_circle
    case number_circle_fill
    case questionmark_circle
    case questionmark_circle_fill
    case exclamationmark_circle
    case exclamationmark_circle_fill
    case xmark_circle
    case xmark_circle_fill
    case checkmark_circle
    case checkmark_circle_fill
    case slash_circle
    case slash_circle_fill
    case dot_circle
    case dot_circle_fill
    case ring_circle
    case ring_circle_fill
    case asterisk_circle
    case asterisk_circle_fill
    // MARK: Arrows Circles
    case arrowtriangle_up_circle
    case arrowtriangle_up_circle_fill
    case arrowtriangle_down_circle
    case arrowtriangle_down_circle_fill
    case arrowtriangle_left_circle
    case arrowtriangle_left_circle_fill
    case arrowtriangle_right_circle
    case arrowtriangle_right_circle_fill
    case chevron_up_circle
    case chevron_up_circle_fill
    case chevron_down_circle
    case chevron_down_circle_fill
    case chevron_left_circle
    case chevron_left_circle_fill
    case chevron_right_circle
    case chevron_right_circle_fill
    case arrow_up_circle
    case arrow_up_circle_fill
    case arrow_down_circle
    case arrow_down_circle_fill
    case arrow_left_circle
    case arrow_left_circle_fill
    case arrow_right_circle
    case arrow_right_circle_fill
    case arrow_up_arrow_down_circle
    case arrow_up_arrow_down_circle_fill
    case arrow_right_arrow_left_circle
    case arrow_right_arrow_left_circle_fill
    case arrow_up_and_down_circle
    case arrow_up_and_down_circle_fill
    case arrow_left_and_right_circle
    case arrow_left_and_right_circle_fill
    case arrow_up_left_circle
    case arrow_up_left_circle_fill
    // Expected:
    /*
     case arrow_up_right_circle
     case arrow_up_right_circle_fill
     */
    // Actual
    /*
     case arrow_upright_circle
     case arrow_up_right_circle_fill
     */
    case arrow_upright_circle
    case arrow_up_right_circle_fill
    case arrow_down_left_circle
    case arrow_down_left_circle_fill
    case arrow_down_right_circle
    case arrow_down_right_circle_fill
    case arrow_uturn_up_circle
    case arrow_uturn_up_circle_fill
    case arrow_uturn_down_circle
    case arrow_uturn_down_circle_fill
    case arrow_uturn_left_circle
    case arrow_uturn_left_circle_fill
    case arrow_uturn_right_circle
    case arrow_uturn_right_circle_fill
    
    // MARK: Squares
    case square
    case square_fill
    case square_lefthalf_fill
    case square_righthalf_fill
    // MARK: ABC Squares
    case a_square
    case a_square_fill
    case b_square
    case b_square_fill
    case c_square
    case c_square_fill
    case d_square
    case d_square_fill
    case e_square
    case e_square_fill
    case f_square
    case f_square_fill
    case g_square
    case g_square_fill
    case h_square
    case h_square_fill
    case i_square
    case i_square_fill
    case j_square
    case j_square_fill
    case k_square
    case k_square_fill
    case l_square
    case l_square_fill
    case m_square
    case m_square_fill
    case n_square
    case n_square_fill
    case o_square
    case o_square_fill
    case p_square
    case p_square_fill
    case q_square
    case q_square_fill
    case r_square
    case r_square_fill
    case s_square
    case s_square_fill
    case t_square
    case t_square_fill
    case u_square
    case u_square_fill
    case v_square
    case v_square_fill
    case w_square
    case w_square_fill
    case x_square
    case x_square_fill
    case y_square
    case y_square_fill
    case z_square
    case z_square_fill
    // MARK: Currency Squares
    case dollarsign_square
    case dollarsign_square_fill
    case centsign_square
    case centsign_square_fill
    case yensign_square
    case yensign_square_fill
    case sterlingsign_square
    case sterlingsign_square_fill
    case francsign_square
    case francsign_square_fill
    case florinsign_square
    case florinsign_square_fill
    case turkishlirasign_square
    case turkishlirasign_square_fill
    case rublesign_square
    case rublesign_square_fill
    case eurosign_square
    case eurosign_square_fill
    case dongsign_square
    case dongsign_square_fill
    case indianrupeesign_square
    case indianrupeesign_square_fill
    case tengesign_square
    case tengesign_square_fill
    case pesetasign_square
    case pesetasign_square_fill
    case pesosign_square
    case pesosign_square_fill
    case kipsign_square
    case kipsign_square_fill
    case wonsign_square
    case wonsign_square_fill
    case lirasign_square
    case lirasign_square_fill
    case australsign_square
    case australsign_square_fill
    case hryvniasign_square
    case hryvniasign_square_fill
    case nairasign_square
    case nairasign_square_fill
    case guaranisign_square
    case guaranisign_square_fill
    case coloncurrencysign_square
    case coloncurrencysign_square_fill
    case cedisign_square
    case cedisign_square_fill
    case cruzeirosign_square
    case cruzeirosign_square_fill
    case tugriksign_square
    case tugriksign_square_fill
    case millsign_square
    case millsign_square_fill
    case sheqelsign_square
    case sheqelsign_square_fill
    case manatsign_square
    case manatsign_square_fill
    case rupeesign_square
    case rupeesign_square_fill
    case bahtsign_square
    case bahtsign_square_fill
    case larisign_square
    case larisign_square_fill
    case bitcoinsign_square
    case bitcoinsign_square_fill
    // MARK: 0-9 Squares
    case _0_square
    case _0_square_fill
    case _1_square
    case _1_square_fill
    case _2_square
    case _2_square_fill
    case _3_square
    case _3_square_fill
    case _4_square
    case _4_square_fill
    case _4_alt_square
    case _4_alt_square_fill
    case _5_square
    case _5_square_fill
    case _6_square
    case _6_square_fill
    case _6_alt_square
    case _6_alt_square_fill
    case _7_square
    case _7_square_fill
    case _8_square
    case _8_square_fill
    case _9_square
    case _9_square_fill
    case _9_alt_square
    case _9_alt_square_fill
    // MARK: 00-50 Squares
    case _00_square
    case _00_square_fill
    case _01_square
    case _01_square_fill
    case _02_square
    case _02_square_fill
    case _03_square
    case _03_square_fill
    case _04_square
    case _04_square_fill
    case _05_square
    case _05_square_fill
    case _06_square
    case _06_square_fill
    case _07_square
    case _07_square_fill
    case _08_square
    case _08_square_fill
    case _09_square
    case _09_square_fill
    case _10_square
    case _10_square_fill
    case _11_square
    case _11_square_fill
    case _12_square
    case _12_square_fill
    case _13_square
    case _13_square_fill
    case _14_square
    case _14_square_fill
    case _15_square
    case _15_square_fill
    case _16_square
    case _16_square_fill
    case _17_square
    case _17_square_fill
    case _18_square
    case _18_square_fill
    case _19_square
    case _19_square_fill
    case _20_square
    case _20_square_fill
    case _21_square
    case _21_square_fill
    case _22_square
    case _22_square_fill
    case _23_square
    case _23_square_fill
    case _24_square
    case _24_square_fill
    case _25_square
    case _25_square_fill
    case _26_square
    case _26_square_fill
    case _27_square
    case _27_square_fill
    case _28_square
    case _28_square_fill
    case _29_square
    case _29_square_fill
    case _30_square
    case _30_square_fill
    case _31_square
    case _31_square_fill
    case _32_square
    case _32_square_fill
    case _33_square
    case _33_square_fill
    case _34_square
    case _34_square_fill
    case _35_square
    case _35_square_fill
    case _36_square
    case _36_square_fill
    case _37_square
    case _37_square_fill
    case _38_square
    case _38_square_fill
    case _39_square
    case _39_square_fill
    case _40_square
    case _40_square_fill
    case _41_square
    case _41_square_fill
    case _42_square
    case _42_square_fill
    case _43_square
    case _43_square_fill
    case _44_square
    case _44_square_fill
    case _45_square
    case _45_square_fill
    case _46_square
    case _46_square_fill
    case _47_square
    case _47_square_fill
    case _48_square
    case _48_square_fill
    case _49_square
    case _49_square_fill
    case _50_square
    case _50_square_fill
    // MARK: Math Symbols Squares
    case plus_square
    case plus_square_fill
    case minus_square
    case minus_square_fill
    case multiply_square
    case multiply_square_fill
    case divide_square
    case divide_square_fill
    case equal_square
    case equal_square_fill
    case greaterthan_square
    case greaterthan_square_fill
    case lessthan_square
    case lessthan_square_fill
    // MARK: General Symbols Squares
    case number_square
    case number_square_fill
    case questionmark_square
    case questionmark_square_fill
    case exclamationmark_square
    case exclamationmark_square_fill
    case xmark_square
    case xmark_square_fill
    case checkmark_square
    case checkmark_square_fill
    // MARK: Arrows squares
    case arrowtriangle_up_square
    case arrowtriangle_up_square_fill
    case arrowtriangle_down_square
    case arrowtriangle_down_square_fill
    case arrowtriangle_left_square
    case arrowtriangle_left_square_fill
    case arrowtriangle_right_square
    case arrowtriangle_right_square_fill
    case chevron_up_square
    case chevron_up_square_fill
    case chevron_down_square
    case chevron_down_square_fill
    case chevron_left_square
    case chevron_left_square_fill
    case chevron_right_square
    case chevron_right_square_fill
    case arrow_up_square
    case arrow_up_square_fill
    case arrow_down_square
    case arrow_down_square_fill
    case arrow_left_square
    case arrow_left_square_fill
    case arrow_right_square
    case arrow_right_square_fill
    case arrow_up_arrow_down_square
    case arrow_up_arrow_down_square_fill
    case arrow_right_arrow_left_square
    case arrow_right_arrow_left_square_fill
    case arrow_up_and_down_square
    case arrow_up_and_down_square_fill
    case arrow_left_and_right_square
    case arrow_left_and_right_square_fill
    case arrow_up_left_square
    case arrow_up_left_square_fill
    case arrow_up_right_square
    case arrow_up_right_square_fill
    case arrow_down_left_square
    case arrow_down_left_square_fill
    case arrow_down_right_square
    case arrow_down_right_square_fill
    case arrow_uturn_up_square
    case arrow_uturn_up_square_fill
    case arrow_uturn_down_square
    case arrow_uturn_down_square_fill
    case arrow_uturn_left_square
    case arrow_uturn_left_square_fill
    case arrow_uturn_right_square
    case arrow_uturn_right_square_fill
    case questionmark_diamond
    case questionmark_diamond_fill
    case triangle
    case triangle_fill
    case triangle_lefthalf_fill
    case triangle_righthalf_fill
    case arrowtriangle_up
    case arrowtriangle_up_fill
    case arrowtriangle_down
    case arrowtriangle_down_fill
    case arrowtriangle_left
    case arrowtriangle_left_fill
    case arrowtriangle_right
    case arrowtriangle_right_fill
    case arrow_up
    case arrow_down
    case arrow_left
    case arrow_right
    case arrow_up_left
    case arrow_up_right
    case arrow_down_left
    case arrow_down_right
    case arrow_up_arrow_down
    case arrow_right_arrow_left
    case arrow_turn_right_up
    case arrow_turn_right_down
    case arrow_turn_down_left
    case arrow_turn_down_right
    case arrow_turn_left_up
    case arrow_turn_left_down
    case arrow_turn_up_left
    case arrow_turn_up_right
    case arrow_uturn_up
    case arrow_uturn_down
    case arrow_uturn_left
    case arrow_uturn_right
    case arrow_up_and_down
    case arrow_left_and_right
    case arrow_up_to_line
    case arrow_down_to_line
    case arrow_left_to_line
    case arrow_right_to_line
    case arrow_up_to_line_alt
    case arrow_down_to_line_alt
    case arrow_left_to_line_alt
    case arrow_right_to_line_alt
    case `return`
    case arrow_clockwise
    case arrow_clockwise_circle
    case arrow_clockwise_circle_fill
    case arrow_counterclockwise
    case arrow_counterclockwise_circle
    case arrow_counterclockwise_circle_fill
    case arrow_up_left_and_arrow_down_right
    case arrow_down_right_and_arrow_up_left
    case arrow_2_squarepath
    case arrow_2_circlepath
    case arrow_2_circlepath_circle
    case arrow_2_circlepath_circle_fill
    case arrow_3_trianglepath
    case leaf_arrow_circlepath
    case arrow_up_right_diamond
    case arrow_up_right_diamond_fill
    case arrow_merge
    case arrow_swap
    case questionmark
    case exclamationmark
    case a
    case textformat_size
    case textformat_alt
    case textformat
    case textformat_subscript
    case textformat_superscript
    case bold
    case italic
    case underline
    case strikethrough
    case bold_italic_underline
    case bold_underline
    case view_2d
    case view_3d
    case text_cursor
    case fx
    case f_cursive
    case sum
    case percent
    case function
    case textformat_abc
    case textformat_abc_dottedunderline
    case textformat_123
    case info
    case info_circle
    case info_circle_fill
    case textbox
    case at
    case at_badge_plus
    case at_badge_minus
    case plus_slash_minus
    case minus_slash_plus
    case plus
    case minus
    case multiply
    case divide
    case equal
    case lessthan
    case greaterthan
    case chevron_left_slash_chevron_right
    case number
    case x_squareroot
    case xmark
    case checkmark
    case plusminus
    case plusminus_circle
    case plusminus_circle_fill
    case chevron_up
    case chevron_down
    case chevron_left
    case chevron_right
    case chevron_left_2
    case chevron_right_2
    case control
    case projective
    case chevron_up_chevron_down
    case chevron_compact_up
    case chevron_compact_down
    case chevron_compact_left
    case chevron_compact_right
    case command
    case option
    case alt
    case delete_right
    case delete_right_fill
    case clear
    case clear_fill
    case delete_left
    case delete_left_fill
    case shift
    case shift_fill
    case capslock
    case capslock_fill
    case eject
    case eject_fill
    case escape
    case circle_bottomthird_split
    case power
    case globe
    case sun_min
    case sun_min_fill
    case sun_max
    case sun_max_fill
    case sunrise
    case sunrise_fill
    case sunset
    case sunset_fill
    case sun_dust
    case sun_dust_fill
    case sun_haze
    case sun_haze_fill
    case moon
    case moon_fill
    case moon_circle
    case moon_circle_fill
    case ZZZ
    case moon_zzz
    case moon_zzz_fill
    case sparkles
    case moon_stars
    case moon_stars_fill
    case cloud
    case cloud_fill
    case cloud_drizzle
    case cloud_drizzle_fill
    case cloud_rain
    case cloud_rain_fill
    case cloud_heavyrain
    case cloud_heavyrain_fill
    case cloud_fog
    case cloud_fog_fill
    case cloud_hail
    case cloud_hail_fill
    case cloud_snow
    case cloud_snow_fill
    case cloud_sleet
    case cloud_sleet_fill
    case cloud_bolt
    case cloud_bolt_fill
    case cloud_sun
    case cloud_sun_fill
    case cloud_sun_rain
    case cloud_sun_rain_fill
    case cloud_sun_bolt
    case cloud_sun_bolt_fill
    case cloud_moon
    case cloud_moon_fill
    case cloud_moon_rain
    case cloud_moon_rain_fill
    case cloud_bolt_rain
    case cloud_bolt_rain_fill
    case cloud_moon_bolt
    case cloud_moon_bolt_fill
    case smoke
    case smoke_fill
    case wind
    case snow
    case wind_snow
    case tornado
    case tropicalstorm
    case hurricane
    case thermometer_sun
    case thermometer_snowflake
    case thermometer
    case light_min
    case light_max
    case rays
    case cursor_rays
    case slowmo
    case timelapse
    case keyboard
    case keyboard_chevron_compact_down
    case rectangle_3_offgrid
    case rectangle_3_offgrid_fill
    case square_grid_3x2
    case square_grid_3x2_fill
    case rectangle_grid_3x2
    case rectangle_grid_3x2_fill
    case square_grid_2x2
    case square_grid_2x2_fill
    case rectangle_grid_2x2
    case rectangle_grid_2x2_fill
    case square_grid_4x3_fill
    case rectangle_grid_1x2
    case rectangle_grid_1x2_fill
    case circle_grid_3x3
    case circle_grid_3x3_fill
    case circle_grid_hex
    case circle_grid_hex_fill
    case checkmark_seal
    case checkmark_seal_fill
    case xmark_seal
    case xmark_seal_fill
    case exclamationmark_triangle
    case exclamationmark_triangle_fill
    case drop_triangle
    case drop_triangle_fill
    case square_and_arrow_up
    case square_and_arrow_up_fill
    case square_and_arrow_down
    case square_and_arrow_down_fill
    case square_and_arrow_up_on_square
    case square_and_arrow_up_on_square_fill
    case square_and_arrow_down_on_square
    case square_and_arrow_down_on_square_fill
    case pencil
    case pencil_circle
    case pencil_circle_fill
    case pencil_slash
    case square_and_pencil
    case pencil_and_ellipsis_rectangle
    case pencil_and_outline
    case trash
    case trash_fill
    case trash_circle
    case trash_circle_fill
    case trash_slash
    case trash_slash_fill
    case folder
    case folder_fill
    case folder_circle
    case folder_circle_fill
    case folder_badge_plus
    case folder_badge_plus_fill
    case folder_badge_minus
    case folder_badge_minus_fill
    case folder_badge_person_crop
    case folder_badge_person_crop_fill
    case paperplane
    case paperplane_fill
    case tray
    case tray_fill
    case tray_and_arrow_up
    case tray_and_arrow_up_fill
    case tray_and_arrow_down
    case tray_and_arrow_down_fill
    case tray_2
    case tray_2_fill
    case tray_full
    case tray_full_fill
    case archivebox
    case archivebox_fill
    case bin_xmark
    case bin_xmark_fill
    case arrow_up_bin
    case arrow_up_bin_fill
    case doc
    case doc_fill
    case arrow_up_doc
    case arrow_up_doc_fill
    case arrow_down_doc
    case arrow_down_doc_fill
    case doc_text
    case doc_text_fill
    case doc_on_doc
    case doc_on_doc_fill
    case doc_on_clipboard
    case doc_on_clipboard_fill
    case doc_richtext
    case doc_plaintext
    case doc_append
    case doc_text_magnifyingglass
    case signature
    case scissors
    case calendar
    case calendar_badge_plus
    case calendar_badge_minus
    case arrowshape_turn_up_left
    case arrowshape_turn_up_left_fill
    case arrowshape_turn_up_left_circle
    case arrowshape_turn_up_left_circle_fill
    case arrowshape_turn_up_right
    case arrowshape_turn_up_right_fill
    case arrowshape_turn_up_right_circle
    case arrowshape_turn_up_right_circle_fill
    case arrowshape_turn_up_left_2
    case arrowshape_turn_up_left_2_fill
    case book
    case book_fill
    case bookmark
    case bookmark_fill
    case rosette
    case paperclip
    case rectangle_and_paperclip
    case link
    case link_circle
    case link_circle_fill
    case personalhotspot
    case pencil_tip
    case pencil_tip_crop_circle
    case pencil_tip_crop_circle_badge_plus
    case pencil_tip_crop_circle_badge_minus
    case person
    case person_fill
    case person_badge_plus
    case person_badge_plus_fill
    case person_badge_minus
    case person_badge_minus_fill
    case person_circle
    case person_circle_fill
    case person_and_person
    case person_and_person_fill
    case person_crop_circle
    case person_crop_circle_fill
    case person_crop_circle_badge_plus
    case person_crop_circle_badge_plus_fill
    case person_crop_circle_badge_minus
    case person_crop_circle_badge_minus_fill
    case person_crop_circle_badge_checkmark
    case person_crop_circle_badge_checkmark_fill
    case person_crop_circle_badge_xmark
    case person_crop_circle_badge_xmark_fill
    case person_crop_circle_badge_exclam
    case person_crop_circle_badge_exclam_fill
    case person_crop_square
    case person_crop_square_fill
    case ear
    case hand_raised
    case hand_raised_fill
    case hand_raised_slash
    case hand_raised_slash_fill
    case hand_thumbsup
    case hand_thumbsup_fill
    case hand_thumbsdown
    case hand_thumbsdown_fill
    case hand_draw
    case hand_draw_fill
    case hand_point_left
    case hand_point_left_fill
    case hand_point_right
    case hand_point_right_fill
    case play
    case play_fill
    case pause
    case pause_fill
    case stop
    case stop_fill
    case playpause
    case playpause_fill
    case backward
    case backward_fill
    case forward
    case forward_fill
    case backward_end
    case backward_end_fill
    case forward_end
    case forward_end_fill
    case backward_end_alt
    case backward_end_alt_fill
    case forward_end_alt
    case forward_end_alt_fill
    case play_circle
    case play_circle_fill
    case pause_circle
    case pause_circle_fill
    case play_rectangle
    case play_rectangle_fill
    case pause_rectangle
    case pause_rectangle_fill
    case memories
    case memories_badge_plus
    case memories_badge_minus
    case shuffle
    case `repeat`
    case repeat_1
    case volume
    case volume_fill
    case volume_slash
    case volume_slash_fill
    case volume_slash_rtl
    case volume_slash_fill_rtl
    case volume_zzz
    case volume_zzz_fill
    case volume_1
    case volume_1_fill
    case volume_2
    case volume_2_fill
    case volume_3
    case volume_3_fill
    case badge_plus_radiowaves_right
    case magnifyingglass
    case magnifyingglass_circle
    case magnifyingglass_circle_fill
    case plus_magnifyingglass
    case minus_magnifyingglass
    case _1_magnifyingglass
    case mic
    case mic_fill
    case mic_circle
    case mic_circle_fill
    case mic_slash
    case mic_slash_fill
    case suit_heart
    case suit_heart_fill
    case suit_club
    case suit_club_fill
    case suit_spade
    case suit_spade_fill
    case suit_diamond
    case suit_diamond_fill
    case heart
    case heart_fill
    case heart_circle
    case heart_circle_fill
    case heart_slash
    case heart_slash_fill
    case heart_slash_circle
    case heart_slash_circle_fill
    case rhombus
    case rhombus_fill
    case star
    case star_fill
    case star_lefthalf_fill
    case star_circle
    case star_circle_fill
    case star_slash
    case star_slash_fill
    case flag
    case flag_fill
    case flag_slash
    case flag_slash_fill
    case location
    case location_fill
    case location_slash
    case location_slash_fill
    case location_north
    case location_north_fill
    case location_circle
    case location_circle_fill
    case location_north_line
    case location_north_line_fill
    case bell
    case bell_fill
    case bell_slash
    case bell_slash_fill
    case tag
    case tag_fill
    case bolt
    case bolt_fill
    case bolt_slash
    case bolt_slash_fill
    case eye
    case eye_fill
    case eye_slash
    case eye_slash_fill
    case list_dash
    case list_bullet
    case list_bullet_indent
    case list_number
    case list_number_rtl
    case text_chevron_left
    case text_chevron_right
    case list_bullet_below_rectangle
    case text_badge_plus
    case text_badge_minus
    case text_badge_checkmark
    case text_badge_xmark
    case text_badge_star
    case text_insert
    case text_append
    case text_quote
    case text_alignleft
    case text_aligncenter
    case text_alignright
    case text_justify
    case text_justifyleft
    case text_justifyright
    case slider_horizontal_3
    case line_horizontal_3
    case line_horizontal_3_decrease
    case line_horizontal_3_decrease_circle
    case line_horizontal_3_decrease_circle_fill
    case icloud
    case icloud_fill
    case icloud_circle
    case icloud_circle_fill
    case icloud_slash
    case icloud_slash_fill
    case exclamationmark_icloud
    case exclamationmark_icloud_fill
    case xmark_icloud
    case xmark_icloud_fill
    case link_icloud
    case link_icloud_fill
    case bolt_horizontal_icloud
    case bolt_horizontal_icloud_fill
    case person_icloud
    case person_icloud_fill
    case lock_icloud
    case lock_icloud_fill
    case arrow_clockwise_icloud
    case arrow_clockwise_icloud_fill
    case arrow_counterclockwise_icloud
    case arrow_counterclockwise_icloud_fill
    case icloud_and_arrow_down
    case icloud_and_arrow_down_fill
    case icloud_and_arrow_up
    case icloud_and_arrow_up_fill
    case ant
    case ant_fill
    case camera
    case camera_fill
    case camera_rotate
    case camera_rotate_fill
    case camera_on_rectangle_fill
    case camera_on_rectangle
    case bubble_right
    case bubble_right_fill
    case bubble_left
    case bubble_left_fill
    case exclamationmark_bubble
    case exclamationmark_bubble_fill
    case quote_bubble
    case quote_bubble_fill
    case t_bubble
    case t_bubble_fill
    case text_bubble
    case text_bubble_fill
    case captions_bubble
    case captions_bubble_fill
    case plus_bubble
    case plus_bubble_fill
    case ellipses_bubble
    case ellipses_bubble_fill
    case bubble_middle_bottom
    case bubble_middle_bottom_fill
    case bubble_middle_top
    case bubble_middle_top_fill
    case bubble_left_and_bubble_right
    case bubble_left_and_bubble_right_fill
    case phone
    case phone_fill
    case phone_circle
    case phone_circle_fill
    case phone_arrow_up_right
    case phone_arrow_up_right_fill
    case phone_arrow_down_left
    case phone_arrow_down_left_fill
    case phone_arrow_right
    case phone_arrow_right_fill
    case phone_badge_plus
    case phone_badge_plus_fill
    case phone_down
    case phone_down_fill
    case phone_down_circle
    case phone_down_circle_fill
    case teletype
    case realtimetext
    case video
    case video_fill
    case video_circle
    case video_circle_fill
    case video_slash
    case video_slash_fill
    case video_badge_plus
    case video_badge_plus_fill
    case arrow_up_right_video
    case arrow_up_right_video_fill
    case arrow_down_left_video
    case arrow_down_left_video_fill
    case questionmark_video
    case questionmark_video_fill
    case questionmark_video_rtl
    case questionmark_video_fill_rtl
    case envelope
    case envelope_fill
    case envelope_circle
    case envelope_circle_fill
    case envelope_open
    case envelope_open_fill
    case envelope_badge
    case envelope_badge_fill
    case gear
    case ellipsis
    case ellipsis_circle
    case ellipsis_circle_fill
    case bag
    case bag_fill
    case bag_badge_plus
    case bag_badge_plus_fill
    case bag_badge_minus
    case bag_badge_minus_fill
    case cart
    case cart_fill
    case cart_badge_plus
    case cart_badge_plus_fill
    case cart_badge_minus
    case cart_badge_minus_fill
    case creditcard
    case creditcard_fill
    case wand_and_rays
    case wand_and_rays_inverse
    case wand_and_stars
    case wand_and_stars_inverse
    case crop
    case crop_rotate
    case skew
    case dial
    case dial_fill
    case nosign
    case gauge
    case gauge_badge_plus
    case gauge_badge_minus
    case speedometer
    case goforward
    case gobackward
    case goforward_10
    case gobackward_10
    case goforward_15
    case gobackward_15
    case goforward_30
    case goforward_45
    case gobackward_45
    case goforward_60
    case gobackward_60
    case goforward_75
    case gobackward_75
    case goforward_90
    case gobackward_90
    case goforward_10_ar
    case gobackward_10_ar
    case goforward_15_ar
    case gobackward_15_ar
    case goforward_30_ar
    case gobackward_30_ar
    case goforward_45_ar
    case gobackward_45_ar
    case goforward_60_ar
    case gobackward_60_ar
    case goforward_75_ar
    case gobackward_75_ar
    case goforward_90_ar
    case gobackward_90_ar
    case goforward_plus
    case gobackward_minus
    case metronome
    case tuningfork
    case paintbrush
    case paintbrush_fill
    case bandage
    case bandage_fill
    case wrench
    case wrench_fill
    case hammer
    case hammer_fill
    case eyedropper
    case eyedropper_halffull
    case eyedropper_full
    case printer
    case printer_fill
    case briefcase
    case briefcase_fill
    case house
    case house_fill
    case music_house
    case music_house_fill
    case lock
    case lock_fill
    case lock_circle
    case lock_circle_fill
    case lock_slash
    case lock_slash_fill
    case lock_open
    case lock_open_fill
    case lock_rotation
    case lock_rotation_open
    case wifi
    case wifi_slash
    case wifi_exclamationmark
    case pin
    case pin_fill
    case pin_slash
    case pin_slash_fill
    case mappin
    case mappin_slash
    case mappin_and_ellipse
    case map
    case map_fill
    case safari
    case safari_fill
    case rotate_left
    case rotate_left_fill
    case rotate_right
    case rotate_right_fill
    case selection_pin_in_out
    case tv
    case tv_fill
    case tv_circle
    case tv_circle_fill
    case tv_music_note
    case tv_music_note_fill
    case desktopcomputer
    case airplayvideo
    case airplayaudio
    case dot_radiowaves_left_and_right
    case dot_radiowaves_right
    case radiowaves_left
    case radiowaves_right
    case antenna_radiowaves_left_and_right
    case music_note
    case music_mic
    case music_note_list
    case guitars
    case car_fill
    case bed_double
    case bed_double_fill
    case hare
    case hare_fill
    case tortoise
    case tortoise_fill
    case film
    case film_fill
    case smiley
    case smiley_fill
    case qrcode
    case barcode
    case viewfinder
    case viewfinder_circle
    case viewfinder_circle_fill
    case barcode_viewfinder
    case qrcode_viewfinder
    case camera_viewfinder
    case faceid
    case doc_text_viewfinder
    case rectangle
    case rectangle_fill
    case photo
    case photo_fill
    case plus_rectangle
    case plus_rectangle_fill
    case minus_rectangle
    case minus_rectangle_fill
    case checkmark_rectangle
    case checkmark_rectangle_fill
    case xmark_rectangle
    case xmark_rectangle_fill
    case person_crop_rectangle
    case person_crop_rectangle_fill
    case rectangle_badge_checkmark
    case rectangle_badge_checkmark_fill
    case rectangle_badge_xmark
    case rectangle_badge_xmark_fill
    case sidebar_left
    case sidebar_right
    case macwindow
    case uiwindow_split_2x1
    case rectangle_dock
    case rectangle_split_3x1
    case rectangle_split_3x1_fill
    case square_split_2x1
    case square_split_2x1_fill
    case square_split_1x2
    case square_split_1x2_fill
    case square_split_2x2
    case square_split_2x2_fill
    case dot_square
    case dot_square_fill
    case squares_below_rectangle
    case rectangle_split_3x3
    case rectangle_split_3x3_fill
    case table
    case table_fill
    case table_badge_more
    case table_badge_more_fill
    case rectangle_on_rectangle
    case rectangle_on_rectangle_fill
    case plus_rectangle_on_rectangle
    case plus_rectangle_on_rectangle_fill
    case photo_on_rectangle
    case photo_on_rectangle_fill
    case rectangle_on_rectangle_angled
    case rectangle_on_rectangle_angled_fill
    case rectangle_stack
    case rectangle_stack_fill
    case rectangle_stack_badge_plus
    case rectangle_stack_badge_plus_fill
    case rectangle_stack_badge_minus
    case rectangle_stack_badge_minus_fill
    case rectangle_stack_person_crop
    case rectangle_stack_person_crop_fill
    case person_2_square_stack
    case person_2_square_stack_fill
    case square_on_square
    case square_on_square_fill
    case plus_square_on_square
    case plus_square_on_square_fill
    case square_on_circle
    case square_on_circle_fill
    case square_stack
    case square_stack_fill
    case pano
    case pano_fill
    case square_and_line_vertical_and_square
    case square_fill_and_line_vertical_square_fill
    case square_fill_and_line_vertical_and_square
    case square_and_line_vertical_and_square_fill
    case flowchart
    case flowchart_fill
    case shield
    case shield_fill
    case shield_lefthalf_fill
    case slider_horizontal_below_rectangle
    case cube
    case cube_fill
    case cube_box
    case cube_box_fill
    case arkit
    case square_stack_3d_down_right
    case square_stack_3d_down_right_fill
    case square_stack_3d_up
    case square_stack_3d_up_fill
    case square_stack_3d_up_slash
    case square_stack_3d_up_slash_fill
    case square_stack_3d_down_dottedline
    case livephoto
    case livephoto_slash
    case livephoto_play
    case scope
    case helm
    case clock
    case clock_fill
    case alarm
    case alarm_fill
    case stopwatch
    case stopwatch_fill
    case timer
    case umbrella
    case umbrella_fill
    case flame
    case flame_fill
    case gamecontroller
    case gamecontroller_fill
    case rectangle_compress_vertical
    case rectangle_expand_vertical
    case rectangle_and_arrow_up_right_and_arrow_down_left
    case rectangle_and_arrow_up_right_and_arrow_down_left_slash
    case chart_bar
    case chart_bar_fill
    case chart_pie
    case chart_pie_fill
    case burst
    case burst_fill
    case waveform_path_ecg
    case waveform_path
    case waveform_path_badge_plus
    case waveform_path_badge_minus
    case waveform
    case staroflife
    case staroflife_fill
    case headphones
    case gift
    case gift_fill
    case app
    case app_fill
    case plus_app
    case plus_app_fill
    case app_badge
    case app_badge_fill
    case app_gift
    case app_gift_fill
    case airplane
    case hourglass
    case hourglass_bottomhalf_fill
    case hourglass_tophalf_fill
    case paragraph
    case purchased
    case purchased_circle
    case purchased_circle_fill
    case exclamationmark_octagon
    case exclamationmark_octagon_fill
    case xmark_octagon
    case xmark_octagon_fill
    case bolt_horizontal
    case bolt_horizontal_fill
    case bolt_horizontal_circle
    case bolt_horizontal_circle_fill
    case perspective
    case grid
    case grid_circle
    case grid_circle_fill
    case burn
    case scribble
    case lasso
    case recordingtape
    case eyeglasses
    case battery_100
    case battery_25
    case battery_0
    
    public var name: String {
        let formattedName = rawValue.replacingOccurrences(of: "_", with: ".")
        if formattedName.first == "." {
            return formattedName
                .dropFirst()
                .map { "\($0)" }
                .reduce("", +)
        }
        
        return formattedName
    }
    
    @available(iOS 13.0, OSX 10.15, tvOS 13.0, watchOS 6.0, *)
    public var image: Image {
        Image(systemName: name)
    }
}
